import type { MapDef, TileType } from "./types";

const W: TileType = 1; // solid wall
const B: TileType = 2; // destructible block
const _: TileType = 0; // floor

export const MAPS: MapDef[] = [
  {
    id: "classic",
    name: "Classic",
    emoji: "🏙️",
    desc: "Original 13×11 layout",
    floorColor: "#388e3c",
    wallColor: "#1b5e20",
    blockColor: "#8d6e63",
    accentColor: "#a5d6a7",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
      [W, _, _, B, B, B, B, B, B, B, _, _, W],
      [W, _, W, B, W, B, W, B, W, B, W, _, W],
      [W, B, B, B, B, B, B, B, B, B, B, B, W],
      [W, B, W, B, W, B, W, B, W, B, W, B, W],
      [W, B, B, B, B, B, B, B, B, B, B, B, W],
      [W, B, W, B, W, B, W, B, W, B, W, B, W],
      [W, B, B, B, B, B, B, B, B, B, B, B, W],
      [W, _, W, B, W, B, W, B, W, B, W, _, W],
      [W, _, _, B, B, B, B, B, B, B, _, _, W],
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
    ] as TileType[][],
  },
  {
    id: "island",
    name: "Island",
    emoji: "🏝️",
    desc: "Open centre, dense edges",
    floorColor: "#f9a825",
    wallColor: "#5d4037",
    blockColor: "#a1887f",
    accentColor: "#fff9c4",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
      [W, _, _, _, B, B, B, B, B, _, _, _, W],
      [W, _, W, B, W, _, W, _, W, B, W, _, W],
      [W, _, B, _, _, _, _, _, _, _, B, _, W],
      [W, B, W, _, W, B, W, B, W, _, W, B, W],
      [W, B, _, _, _, _, _, _, _, _, _, B, W],
      [W, B, W, _, W, B, W, B, W, _, W, B, W],
      [W, _, B, _, _, _, _, _, _, _, B, _, W],
      [W, _, W, B, W, _, W, _, W, B, W, _, W],
      [W, _, _, _, B, B, B, B, B, _, _, _, W],
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
    ] as TileType[][],
  },
  {
    id: "maze",
    name: "Maze",
    emoji: "🌀",
    desc: "Tight corridors",
    floorColor: "#4a148c",
    wallColor: "#1a0033",
    blockColor: "#7b1fa2",
    accentColor: "#ce93d8",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
      [W, _, _, B, _, B, _, B, _, B, _, _, W],
      [W, _, W, W, W, B, W, B, W, W, W, _, W],
      [W, B, W, _, _, _, _, _, _, _, W, B, W],
      [W, _, W, _, W, W, _, W, W, _, W, _, W],
      [W, B, _, _, W, _, _, _, W, _, _, B, W],
      [W, _, W, _, W, W, _, W, W, _, W, _, W],
      [W, B, W, _, _, _, _, _, _, _, W, B, W],
      [W, _, W, W, W, B, W, B, W, W, W, _, W],
      [W, _, _, B, _, B, _, B, _, B, _, _, W],
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
    ] as TileType[][],
  },
  {
    id: "chaos",
    name: "Chaos",
    emoji: "💥",
    desc: "Almost all blocks — destroy everything!",
    floorColor: "#b71c1c",
    wallColor: "#4e0000",
    blockColor: "#e53935",
    accentColor: "#ff8a80",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
      [W, _, _, B, B, B, B, B, B, B, _, _, W],
      [W, _, W, B, W, B, W, B, W, B, W, _, W],
      [W, B, B, B, B, B, B, B, B, B, B, B, W],
      [W, B, W, B, W, B, W, B, W, B, W, B, W],
      [W, B, B, B, B, _, _, _, B, B, B, B, W],
      [W, B, W, B, W, B, W, B, W, B, W, B, W],
      [W, B, B, B, B, B, B, B, B, B, B, B, W],
      [W, _, W, B, W, B, W, B, W, B, W, _, W],
      [W, _, _, B, B, B, B, B, B, B, _, _, W],
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
    ] as TileType[][],
  },
];
